using System.Diagnostics;
using System.IO;

namespace DiplomaWebApp.Python
{
    public class RunCmd
    {
        public RunCmdResult Run(string cmd, string args)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "python";
            start.Arguments = string.Format("\"{0}\" \"{1}\"", cmd, args);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    RunCmdResult runCmdResult = new RunCmdResult();

                    runCmdResult.Errors = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    runCmdResult.Result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    return runCmdResult;
                }
            }
        }
    }
}
